### ISSUE TITLE
IE8 - inconsistent navigation tool tips font

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-kineo-theme#3]
Tool tip display in default arial font except PLP which displays in Roboto font. 

![screen shot 2015-01-08 at 10 31 09](https://cloud.githubusercontent.com/assets/7045330/5661471/13b32482-9724-11e4-9d88-ea91b2a7d6cb.png)

**Comment by guywillis** [comment]
Tooltips are no longer supported by default in the theme.
