### ISSUE TITLE
IE8 - Matching dropdown icon not visible until hover

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-kineo-theme#5]
Drop down icon on matching isn't visible until hover.
![screen shot 2015-01-08 at 10 38 26](https://cloud.githubusercontent.com/assets/7045330/5661511/89a0ed46-9724-11e4-962e-59fbdad71905.png)

**Comment by guywillis** [comment]
No longer an issue in the latest version of the theme.
