### ISSUE TITLE
IE8 - component alignment issues

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-kineo-theme#7]
I've noticed an issue on both the accordion and matching component where the alignment is off. This only appears to be an issue with half width components (left/right).

On accordion the body is pushed out by 1px.
![screen shot 2015-01-08 at 10 32 40](https://cloud.githubusercontent.com/assets/7045330/5661672/60f87c0e-9726-11e4-9eae-d8820f39777a.png)

On matching the select container is pushed out by 1px.
![screen shot 2015-01-08 at 10 38 26](https://cloud.githubusercontent.com/assets/7045330/5661679/6a86bc5e-9726-11e4-9a45-65b806febbd5.png)

**Comment by guywillis** [comment]
No longer an issue in the latest version of the theme.
